png(filename = "Plot4.png")
  par(mfrow=c(2,2),mar=c(5, 4, 4, 2) + 0.1,mai=c(1,0.6806,0.6806,0.3486))
  plot(powerdt$DateTime,powerdt$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)",main="")
  plot(powerdt$DateTime,powerdt$Voltage,type="l",xlab="datetime",ylab="Voltage")
  plot(powerdt$DateTime,powerdt$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
  lines(powerdt$DateTime,powerdt$Sub_metering_1)
  lines(powerdt$DateTime,powerdt$Sub_metering_2,col="red")
  lines(powerdt$DateTime,powerdt$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
  plot(powerdt$DateTime,powerdt$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()